import "dotenv/config";

const BASE_URL_BACKEND = 'http://localhost:3005';
const BASE_URL_FRONTEND = 'http://localhost:3000';
const BASE_URL_NGINX = 'http://192.168.0.5:8080'
const BASE_URL_SERVER_WPS = '192.168.1.86'
const BASE_URL_SERVER_DATABASE = '192.168.0.6'
const BASE_URL_SERVER_NGINX = '192.168.0.5'

export const config = {
  BASE_URL_BACKEND,
  BASE_URL_FRONTEND,
  BASE_URL_NGINX,
  BASE_URL_SERVER_WPS,
  BASE_URL_SERVER_DATABASE,
  BASE_URL_SERVER_NGINX,
  URL_API_MILVUS: `${BASE_URL_BACKEND}/api/milvus`,
  REMOTE_WPS_SERVICE: `${BASE_URL_BACKEND}/status`,
  HOMEPAGE_URL_FRONTEND_ADMIN: `${BASE_URL_FRONTEND}/admin/home`,
  LOGIN_URL_FRONTEND: `${BASE_URL_FRONTEND}/login`,
  HOMEPAGE_URL_FRONTEND_HOME: `${BASE_URL_FRONTEND}/home`,
  PORT_HTTPS:3006,
  PORT_HTTP:3005
};
